### PR TITLE
Hotfix Completed && Audio Capability Added

### PR DESCRIPTION
**Pull request by Parallaxes**
Here's a quick summary of a changes:

- I added ability to play music when loading levels (embedded when loading the background for a level), all you have to do is:
1. Add this line to the top of the background file (I used `BackgroundSnow.js` for our level): 
```js
import GameEnv from './GameEnv.js';
```
2. Add this under the `constructor` for the background class. Example:
```js
export class BackgroundSnow extends Background {
    constructor(canvas, image, data) {
        super(canvas, image, data);

        // Start the background music in loop
        GameEnv.loopSound("everlong");

        this.parallaxSpeed = 0.3; // Speed for vertical parallax scrolling
    }
```

You can play sounds by their **ID Tags**, which are loaded in in `index.md`.

The current abilities for audio are as follows:
- Playing a sound (native, I did not add this) using `GameEnv.playSound()`
- Looping a sound using `GameEnv.loopSound()`
- Stopping all sounds using `GameEnv.stopAllSounds()`

- I also uploaded the song Everlong by Foo Fighters

### CODE REVIEW

**Comment by Parallaxes** [comment]
Reviewing my own code... should be ok right?

LGTM! 😸

**Comment by ackpit** [comment]
nyuhuh stinker

**Comment by buythesenbundle** [comment]
is this rizz

> nyuhuh stinker

**Comment by Parallaxes** [comment]
> is this rizz
> 
> > nyuhuh stinker

not quite my tempo

**Pull request merged**
